### recuperar usuario por ID
GET http://localhost:3000/users/xesuspb@gmail.com

### postear usuario
POST http://localhost:3000/users
Content-Type: application/json

{
"email": "xesuspb@gmail.com",
"nombre": "Jesús",
"apellidos": "Bañobre",
"telefono": 647736793
}

### actualizar usuario
PATCH http://localhost:3000/users/xesuspb@gmail.com
Content-Type: application/json

{
    "email": "xesuspb@gmail.com",
    "nombre": "Anfetas",
    "apellidos": "Cósmicas",
    "telefono": 231313123
}

### eliminar usuario
DELETE  http://localhost:3000/users/xesuspb@gmail.com





### Recuperar alojamientos
GET http://localhost:3000/alojamientos

### Recuperar alojamiento por ID
GET http://localhost:3000/alojamientos/5c364fa6-1af2-419a-86d1-43adb0b11acd

### Recuperar alojamientos asociados a un usuario
GET http://localhost:3000/alojamientos?userEmail=anfetas@gmail.com

### Publicar un alojamiento
POST http://localhost:3000/alojamientos
Content-Type: application/json

{
    "id": "5c364fa6-1af2-419a-86d1-43adb0b11acd",
    "nombre": "Locura máxima",
    "userEmail": "xesuspb@gmail.com",
    "descripcion": "Loqueando a tope",
    "imgURL": [
        "https://ethic.es/wp-content/uploads/2023/03/imagen.jpg"
    ],
    "animales": false,
    "ubicacion": "(92, 189)"
}

### Eliminar un alojamiento
DELETE http://localhost:3000/alojamientos/5c364fa6-1af2-419a-86d1-43adb0b11acd





### Recuperar reserva por id
GET http://localhost:3000/reservas/414e208b-d10e-483c-9fa4-10056933a9fb

### Recuperar reservas por email
GET http://localhost:3000/reservas?email=xesuspb@gmail.com

### Añadir reserva
POST http://localhost:3000/reservas/
Content-Type: application/json

{
    "id": "414e208b-d10e-483c-9fa4-10056933a9fb",
    "userEmail": "xesuspb@gmail.com",
    "alojamientoId": "df3f6537-c757-4420-862c-778be30ab5fc",
    "fechaInicio": "Lunes",
    "fechaFin": "Martes"
}

### Eliminar reserva
DELETE http://localhost:3000/reservas/414e208b-d10e-483c-9fa4-10056933a9fb