### recuperar usuario por ID
GET http://localhost:3000/users/xesuspb@gmail.com

### postear usuario
POST http://localhost:3000/users
Content-Type: application/json

{
"email": "xesuspb@gmail.com",
"nombre": "Jesús",
"apellidos": "Bañobre",
"telefono": 647736793
}

### actualizar usuario
PATCH http://localhost:3000/users/xesuspb@gmail.com
Content-Type: application/json

{
    "email": "xesuspb@gmail.com",
    "nombre": "Anfgetas",
    "apellidos": "Cósmicas",
    "telefono": 231313123
}